<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <ApplicationIcon />
    <StartupObject />
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Installer1.cs" />
    <Compile Update="Installer1.Designer.cs">
      <DependentUpon>Installer1.cs</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Core.System.Configuration.Install" Version="1.1.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
    <PackageReference Include="System.Management" Version="9.0.0" />
    <PackageReference Include="System.Security.AccessControl" Version="6.0.1" />
  </ItemGroup>
</Project>